### ISSUE TITLE
make the grey bar at top slightly transparent

### ISSUE THREAD

**Issue by simonegiacco** [afterwire/evidenceaction#46]
grey bar at top on home page goes from opaque when big to slightly transparent when it gets smaller - suggest that it be made slightly transparent for both

**Comment by afterwire** [comment]
@evidenceaction2 This is what that would look like. It might be a bit different to what you were expecting because by default the top nav bar doesn't sit on top of the image but in fact on top of a white background.

![topbar](https://user-images.githubusercontent.com/46914245/57052922-df2eea00-6ccd-11e9-9633-35ef8ad60664.gif)
